name: Server workflow

on:
  push: 

env:
  PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  GOERLI_RPC_URL: ${{secrets.GOERLI_RPC_URL}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
  COINMARKERCAP_API: ${{secrets.COINMARKERCAP_API}}
  MAINNET_RPC_URL: ${{secrets.MAINNET_RPC_URL}}
  TEST_PRIVATE_KEY: ${{secrets.TEST_PRIVATE_KEY}}
  SEPOLIA_RPC_URL: ${{secrets.SEPOLIA_RPC_URL}}
  POLYGON_RPC_URL: ${{secrets.POLYGON_RPC_URL}}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn --ignore-scripts
        shell: bash
      - name: Create local node and deploy
        run: |
          yarn hardhat node &
          yarn hardhat deploy --network localhost
      - name: Run Tests
        run: yarn hardhat test     

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test --no-match-path "test/foundry/invariants/*.t.sol" -vvv